# Generated by Django 2.2.2 on 2019-07-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190722_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('CANADA', 'Canada'), ('USA', 'USA'), ('UNITED KINGDOM', 'United Kingdom'), ('AUSTRALIA', 'Australia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NON-BINARY', 'Non-Binary')], max_length=10),
        ),
    ]
