# Generated by Django 2.2.2 on 2019-07-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190722_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
    ]
