# Generated by Django 2.2.2 on 2019-08-27 15:25

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190724_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education_attainment',
            field=models.TextField(choices=[('Some high school', 'Some high school'), ('High school diploma or equivalent', 'High school diploma or equivalent'), ('Trades certification', 'Trades certification'), ('College diploma', 'College diploma'), ('Bachelor’s degree', 'Bachelor’s degree'), ('Graduate degree', 'Graduate degree'), ('Professional degree', 'Professional degree')], null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ethnicity',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='income',
            field=models.TextField(choices=[('$0 - $34,999', '$0 - $34,999'), ('$35,000 - $49,999', '$35,000 - $49,999'), ('$50,000 - $69,999', '$50,000 - $69,999'), ('$70,000 - $99,999', '$70,000 - $99,999'), ('$100,000 - $149,999', '$100,000 - $149,999'), ('$150,000 - $249,999', '$150,000 - $249,999'), ('$250,000 or more', '$250,000 or more')], null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
