# Generated by Django 2.2.2 on 2019-09-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190904_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='screen_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
