# Generated by Django 2.2.2 on 2019-10-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='urbanization',
            field=models.CharField(choices=[('Major Metropolitan Area', 'Major Metropolitan Area'), ('Small City/Town', 'Small City/Town'), ('Rural Area', 'Rural Area')], max_length=30, null=True),
        ),
    ]
