# Generated by Django 2.2.2 on 2019-10-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_urbanization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='education_attainment',
            field=models.TextField(choices=[('No high school diploma or equivalent', 'No high school diploma or equivalent'), ('High school (secondary school) diploma or equivalent', 'High school (secondary school) diploma or equivalent'), ('Certificate of Apprenticeship or Certificate of Qualification or other trades certificate or diploma', 'Certificate of Apprenticeship or Certificate of Qualification or other trades certificate or diploma'), ('College, CEGEP or other non-university certificate or diploma', 'College, CEGEP or other non-university certificate or diploma'), ('University certificate, diploma or degree at the bachelor level or below', 'University certificate, diploma or degree at the bachelor level or below'), ("Degree in medicine, dentistry, veterinary medicine or optometry (M.D., D.D.S., D.M.D., D.V.M., O.D.), master's degree (e.g., M.A., M.Sc., M.Ed., M.B.A.) or earned doctorate (e.g., Ph.D.)", "Degree in medicine, dentistry, veterinary medicine or optometry (M.D., D.D.S., D.M.D., D.V.M., O.D.), master's degree (e.g., M.A., M.Sc., M.Ed., M.B.A.) or earned doctorate (e.g., Ph.D.)")], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ethnicity',
            field=models.TextField(choices=[('White', 'White'), ('South Asian (e.g., East Indian, Pakistani, Sri Lankan, etc.)', 'South Asian (e.g., East Indian, Pakistani, Sri Lankan, etc.)'), ('Chinese', 'Chinese'), ('Black', 'Black'), ('Filipino', 'Filipino'), ('Latin American', 'Latin American'), ('Arab', 'Arab'), ('Southeast Asian (e.g., Vietnamese, Cambodian, Laotian, Thai, etc.)', 'Southeast Asian (e.g., Vietnamese, Cambodian, Laotian, Thai, etc.)'), ('West Asian (e.g., Iranian, Afghan, etc.)', 'West Asian (e.g., Iranian, Afghan, etc.)'), ('Korean', 'Korean'), ('Japanese', 'Japanese'), ('Other', 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='urbanization',
            field=models.CharField(choices=[('Large urban centre (population 100,000 or more)', 'Large urban centre (population 100,000 or more)'), ('Medium population centres (population 30,000 to 99,999)', 'Medium population centres (population 30,000 to 99,999)'), ('Small population centres (population 1,000 to 29,999)', 'Small population centres (population 1,000 to 29,999)'), ('Rural Area', 'Rural Area')], max_length=30, null=True),
        ),
    ]
