# Generated by Django 2.2.2 on 2019-10-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191024_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ethnicity',
            field=models.TextField(choices=[('White', 'White'), ('South Asian (e.g., East Indian, Pakistani, Sri Lankan, etc.)', 'South Asian (e.g., East Indian, Pakistani, Sri Lankan, etc.)'), ('Chinese', 'Chinese'), ('Black', 'Black'), ('Filipino', 'Filipino'), ('Latin American', 'Latin American'), ('Arab', 'Arab'), ('Southeast Asian (e.g., Vietnamese, Cambodian, Laotian, Thai, etc.)', 'Southeast Asian (e.g., Vietnamese, Cambodian, Laotian, Thai, etc.)'), ('West Asian (e.g., Iranian, Afghan, etc.)', 'West Asian (e.g., Iranian, Afghan, etc.)'), ('Korean', 'Korean'), ('Japanese', 'Japanese'), ('Other', 'Other'), ('', '')], null=True),
        ),
    ]
