runtime: python
env: flex
entrypoint: gunicorn -b :$PORT classapp.wsgi

beta_settings:
    cloud_sql_instances: sentence-class-app:northamerica-northeast1:classification-app

runtime_config:
  python_version: 3