# Generated by Django 2.2.2 on 2019-06-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSentence',
            fields=[
                ('id', models.FloatField(blank=True, primary_key=True, serialize=False)),
                ('sentence', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'class_sentence',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Sentences',
        ),
    ]
