# Generated by Django 2.2.2 on 2019-11-14 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0004_classified_inprogress_notstarted_sentences_undetermined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inprogress',
            options={'managed': True},
        ),
    ]
