# Generated by Django 2.2.2 on 2019-11-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0005_auto_20191114_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='inprogress',
            name='sentence',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='inprogress',
            name='sentenceid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
