# Generated by Django 2.2.2 on 2019-11-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0006_auto_20191114_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inprogress',
            name='income',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
