# Generated by Django 2.2.2 on 2019-11-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0007_auto_20191118_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('sentenceid', models.IntegerField(blank=True, null=True)),
                ('classification', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
