# Generated by Django 2.2.2 on 2019-11-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0008_userresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassSentence',
        ),
    ]
