# Generated by Django 2.2.2 on 2019-06-14 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sentences', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questions.Questions')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sentences.Sentences')),
            ],
        ),
    ]
