# Generated by Django 2.2.2 on 2019-06-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_auto_20190617_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='response',
            field=models.BooleanField(default=True),
        ),
    ]
