# Generated by Django 2.2.2 on 2019-06-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0003_responses_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='userId',
            field=models.IntegerField(null=True),
        ),
    ]
