# Generated by Django 2.2.2 on 2019-09-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0005_auto_20190722_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='response',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
