# Generated by Django 2.2.2 on 2019-09-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0007_auto_20190912_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('sentence', models.TextField()),
                ('response', models.CharField(max_length=15, null=True)),
                ('userId', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('postal_code', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Responses',
        ),
    ]
