# Generated by Django 2.2.2 on 2019-09-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0010_totals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totals',
            name='username',
        ),
        migrations.AddField(
            model_name='authresponses',
            name='screen_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='careresponses',
            name='screen_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fairresponses',
            name='screen_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libresponses',
            name='screen_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loyresponses',
            name='screen_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sanresponses',
            name='screen_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='totals',
            name='screen_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
