# Generated by Django 2.2.2 on 2019-10-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0014_auto_20190920_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authresponses',
            name='response',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='careresponses',
            name='response',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fairresponses',
            name='response',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='libresponses',
            name='response',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='loyresponses',
            name='response',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sanresponses',
            name='response',
            field=models.TextField(null=True),
        ),
    ]
